version: "3.7"
services:
  telegraf:
    image: docker.io/telegraf:1.19
    container_name: telegraf
    command:
      - "bash"
      - "-xe"
      - "/tmp/entrypoint.sh"
    restart: unless-stopped
    environment: 
      - POWERWALL_PASS=${POWERWALL_PASS}
      - POWERWALL_LOCATION=${POWERWALL_LOCATION}
    volumes:
      - ./telegraf/entrypoint.sh:/tmp/entrypoint.sh:z
      - ./telegraf/etc:/etc/telegraf:z
      - ./powerwall_auth:/tmp/cookie:z
    extra_hosts:
      - powerwall:${POWERWALL_IP}
  influxdb:
    image: docker.io/influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    volumes:
        - ./influxdb/etc:/etc/influxdb
        - /srv/powerwall/influxdb:/var/lib/influxdb:z
  grafana:
    image: docker.io/grafana/grafana:7.5.10
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=powerwall
      - GF_SECURITY_ADMIN_PASSWORD=powerwall
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - POWERWALL_LOCATION=${POWERWALL_LOCATION}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:z
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:z
      - ./grafana/baked:/var/lib/grafana/dashboards:z
