version: "3.7"
services:
  telegraf:
    image: docker.io/telegraf:1.19
    container_name: telegraf
    # command:
    # curl script from NGINX sidecar & execute - script should call:
    # /usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d &
    # Script for cookie/token generation
    restart: unless-stopped
    volumes:
      - ./telegraf/etc:/etc/telegraf:z
      - ./powerwall_auth:/tmp/cookie:z
    extra_hosts:
      - "powerwall:192.168.1.92"
  influxdb:
    image: docker.io/influxdb:1.8
    container_name: influxdb
    ports:
        - 8086:8086
    restart: unless-stopped
    volumes:
        - ./influxdb/etc:/etc/influxdb
        - /srv/powerwall/influxdb:/var/lib/influxdb:z
  grafana:
    image: docker.io/grafana/grafana:7.5.10
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=powerwall
      - GF_SECURITY_ADMIN_PASSWORD=powerwall
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - POWERWALL_HOST=powerwall
      - POWERWALL_LOCATION="lat=29.7231806&lon=-82.5562896"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:z
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:z
      - ./grafana/baked:/var/lib/grafana/dashboards:z
      - /srv/powerwall/grafana:/var/lib/grafana:z
