name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose --env-file .envsample up -d
      - name: Pause and list containers
        run: sleep 10 && docker ps -a
      - name: Investigate failures
        run: docker logs grafana
      - name: Test
        run: docker run --network container:grafana appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/